apiVersion: v1
kind: Pod
metadata:
  name: hostpath-demo
  namespace: finance
spec:
  containers:
  - name: node-log-reader
    image: nginx:1.25-alpine
    command: ["/bin/sh", "-c", "while true; do sleep 3600; done"]
    volumeMounts:
    - name: node-logs
      mountPath: /app/host-logs    # Path inside the container
      readOnly: true               # Recommended safety measure for hostPath
  volumes:
  - name: node-logs
    hostPath:
      path: /var/log               # Actual directory path on the host worker node
      type: Directory              # Checks that /var/log exists as a directory
