FROM centos
LABEL description="This is a container image for kubernetes"
RUN yum update -y
RUN yum instlal httpd -y
ENV dir /var/www/html
COPY ./index.html $dir
CMD ["/usr/sbin/httpd","-D","FOREGROUND"]
