apiVersion: v1
kind: Pod
metadata:
  name: lb-pod-example
  labels:
    app: lb-pod-example
spec:
  containers:
  - name: lb-pod-example-container
    image: dgruploads/tomcat-image
    ports:
    - name: tomcatport
      containerPort: 8080
