apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-processor-dev
  namespace: finance
spec:
  replicas: 1
  selector:
    matchLabels:
      app: processor-worker-dev
  template:
    metadata:
      labels:
        app: processor-worker-dev
    spec:
      containers:
      - name: app-container
        image: nginx:1.25-alpine
        envFrom:
        - configMapRef:
            name: app-configuration-dev
        volumeMounts:
        - name: config-volume
          mountPath: /app/config
      volumes:
      - name: config-volume
        configMap:
          name: app-configuration-dev
          items:
          - key: ui.properties
            path: ui.properties
